const db = require('./db');
const expressModule = require('express');
const originalExpress = expressModule;

function getToken(req) { return req.headers.authorization?.split(' ')[1] || ''; }
async function findUser(req) {
  const token = getToken(req); if (!token) return null;
  const users = (await db.get('users')) || {};
  const username = Object.keys(users).find(k => users[k] && users[k].token === token);
  return username ? { users, username, user: users[username] } : null;
}
function moveLayersBeforeCatchAll(app, layers) {
  const stack = app._router?.stack || [];
  for (const layer of layers) { const index = stack.indexOf(layer); if (index >= 0) stack.splice(index, 1); }
  const catchIndex = stack.findIndex(layer => layer.route && layer.route.path === '*');
  if (catchIndex >= 0) stack.splice(catchIndex, 0, ...layers); else stack.push(...layers);
}
function registerActivityRoutes(app) {
  if (app.__sorokibaActivityRoutes) return; app.__sorokibaActivityRoutes = true; const addedLayers = [];
  app.get('/api/me/recovery-status', async (req,res)=>{try{const found=await findUser(req);if(!found)return res.status(401).json({error:'Token inválido'});res.json({configured:Boolean(found.user.recoveryCode)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível verificar o código de recuperação.'});}}); addedLayers.push(app._router.stack[app._router.stack.length-1]);
  app.post('/api/me/recovery-code', async (req,res)=>{try{const{currentPassword,recoveryCode}=req.body||{};if(!currentPassword||!recoveryCode)return res.status(400).json({error:'Preencha a senha atual e o código de recuperação.'});const found=await findUser(req);if(!found)return res.status(401).json({error:'Token inválido'});if(found.user.password!==currentPassword)return res.status(401).json({error:'Senha atual incorreta.'});found.user.recoveryCode=String(recoveryCode);await db.set('users',found.users);res.json({message:'Código de recuperação salvo com sucesso!'});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível salvar o código agora.'});}}); addedLayers.push(app._router.stack[app._router.stack.length-1]);
  app.get('/api/mayor/users',async(req,res)=>{try{if(!req.user)return res.status(401).json({error:'Token inválido'});if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});const users=(await db.get('users'))||{};const list=Object.values(users).filter(user=>user&&user.username!==req.user.username&&!user.isMayor).map(user=>({name:user.name,username:user.username,jobName:user.jobName||'Estudante',level:user.level||1,xp:user.xp||0,money:user.money||0}));res.json({users:list});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível carregar as contas.'});}}); addedLayers.push(app._router.stack[app._router.stack.length-1]);
  app.delete('/api/mayor/users/:username',async(req,res)=>{try{if(!req.user||!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode excluir contas'});const targetUsername=decodeURIComponent(req.params.username);if(targetUsername===req.user.username)return res.status(400).json({error:'O prefeito não pode excluir a própria conta.'});const users=(await db.get('users'))||{};const target=users[targetUsername];if(!target)return res.status(404).json({error:'Conta não encontrada.'});if(target.isMayor)return res.status(403).json({error:'A conta do prefeito não pode ser excluída por este painel.'});delete users[targetUsername];await db.set('users',users);const city=(await db.get('city'))||{};if(target.countedInPopulation){city.population=Math.max(0,Number(city.population||0)-1);await db.set('city',city);}res.json({message:`Conta de ${target.name||targetUsername} excluída com sucesso!`,population:city.population});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível excluir a conta agora.'});}}); addedLayers.push(app._router.stack[app._router.stack.length-1]);
  app.get('/admin-delete.js',(req,res)=>{try{const fs=require('fs'),path=require('path');res.type('application/javascript').send(fs.readFileSync(path.join(process.cwd(),'admin-delete.js'),'utf8'));}catch(e){console.error(e);res.status(500).send('// Erro ao carregar painel');}}); addedLayers.push(app._router.stack[app._router.stack.length-1]);
  moveLayersBeforeCatchAll(app,addedLayers);
}
const wrappedExpress=function(...args){const app=originalExpress(...args);const originalListen=app.listen.bind(app);app.listen=function(...listenArgs){registerActivityRoutes(app);const fs=require('fs'),path=require('path');if(!app.__sorokibaSendFilePatched){app.__sorokibaSendFilePatched=true;app.use((req,res,next)=>{const original=res.sendFile.bind(res);res.sendFile=function(filePath,options,callback){try{if(path.basename(filePath)==='index.html'){let html=fs.readFileSync(filePath,'utf8');if(!html.includes('admin-delete.js'))html=html.replace('</body>','<script src="/admin-delete.js"></script></body>');res.type('html').send(html);return;}}catch(e){console.error(e)}return original(filePath,options,callback);};next();});const stack=app._router?.stack||[];moveLayersBeforeCatchAll(app,[stack[stack.length-1]]);}return originalListen(...listenArgs);};return app;};
Object.assign(wrappedExpress,originalExpress);
const originalStatic=originalExpress.static;
wrappedExpress.static=function(root,options){const middleware=originalStatic(root,options);return function(req,res,next){if(req.path==='/app.js'){try{const fs=require('fs'),path=require('path');let source=fs.readFileSync(path.join(root,'app.js'),'utf8');const oldBlock=`if (d.correct) {\n     toast(d.message);\n   } else {\n     openModal(\`<h2>\${d.message}</h2><p>Resposta correta: <b>\${esc(d.correctOptionText || d.correctIndex)}</b></p><button class="primary" onclick="closeModal()">Fechar</button>\`);\n   }`;const newBlock=`if (!d.correct) {\n     openModal(\`<h2>\${d.message}</h2><p>Resposta correta: <b>\${esc(d.correctOptionText || d.correctIndex)}</b></p><button class="primary" onclick="window.__missionFeedbackResolve && window.__missionFeedbackResolve()">Continuar</button>\`);\n     await new Promise(resolve => { window.__missionFeedbackResolve = resolve; });\n     window.__missionFeedbackResolve = null;\n     closeModal();\n   } else {\n     toast(d.message);\n   }`;if(source.includes(oldBlock))source=source.replace(oldBlock,newBlock);const missionUiPath=path.join(root,'mission-ui.js');if(fs.existsSync(missionUiPath))source+=`\n\n${fs.readFileSync(missionUiPath,'utf8')}\n`;res.type('application/javascript').send(source);return;}catch(e){console.error('Falha ao ajustar app.js',e)}}middleware(req,res,next);};};
require.cache[require.resolve('express')].exports=wrappedExpress;
const Module=require('module');const originalLoader=Module._extensions['.js'];
Module._extensions['.js']=function(module,filename){
  if(filename.endsWith('/server.js')){
    const fs=require('fs');let source=fs.readFileSync(filename,'utf8');
    source=source.replace(/Date\.now\(\) \+ 3600 \* 1000/g,'Date.now() + 1800 * 1000');
    source=source.replace(/Aguarde 1 hora para receber mais 2 missões/g,'Aguarde 30 minutos para receber mais 2 missões');
    source=source.replace(/city\.proposals\.push\(\{id:`prop_\$\{Date\.now\(\)\}`,author:req\.user\.name,/g,'city.proposals.push({id:`prop_${Date.now()}`,author:req.user.name,authorUsername:req.user.username,');
    source=source.replace("transactions:[],answeredQuestions:[],missionStarts:[]","transactions:[],answeredQuestions:[],answerHistory:[],professionalXpByJob:{estudante:0},missionStarts:[]");
    // Substitui a criação de missão por uma versão tolerante a contas antigas e dados incompletos.
    source=source.replace(/const createMission=.*?\n\napp\.post\('\/api\/register'/s,`const createMission=(jobId,username)=>{const user=users[username];if(!user)return null;if(!Array.isArray(user.answeredQuestions))user.answeredQuestions=[];if(!Array.isArray(user.answerHistory))user.answerHistory=[];if(!user.questionUsage||typeof user.questionUsage!=='object')user.questionUsage={};if(!user.professionalXpByJob||typeof user.professionalXpByJob!=='object')user.professionalXpByJob={};if(!Number.isFinite(Number(user.professionalXpByJob[jobId])))user.professionalXpByJob[jobId]=0;const cfg=(city.missionRewards&&city.missionRewards[jobId])||{questionsPerMission:2,xpPerMission:50,moneyPerMission:50};const count=Math.max(1,Number(cfg.questionsPerMission)||2);const sourceQuestions=(questionBank[jobId]&&questionBank[jobId].length?questionBank[jobId]:questionBank.generic)||[];if(!sourceQuestions.length)return null;const professionXp=Number(user.professionalXpByJob[jobId]||0);const maxDifficulty=professionXp<100?1:professionXp<200?2:professionXp<400?3:professionXp<700?4:professionXp<1000?5:6;let jobQuestions=sourceQuestions.filter(q=>Number(q.difficulty||1)<=maxDifficulty);if(!jobQuestions.length)jobQuestions=sourceQuestions.slice();let pool=jobQuestions.filter(q=>Number(user.questionUsage[q.id]||0)<2&&!user.answerHistory.includes(q.id)&&!user.answeredQuestions.includes(q.id));if(pool.length<count)pool=jobQuestions.filter(q=>Number(user.questionUsage[q.id]||0)<2&&!user.answerHistory.includes(q.id));if(pool.length<count)pool=jobQuestions.slice();const n=Math.min(count,pool.length);const chosen=[];const poolCopy=pool.slice();for(let i=0;i<n;i++){chosen.push(poolCopy.splice(Math.floor(Math.random()*poolCopy.length),1)[0]);}for(const q of chosen){user.questionUsage[q.id]=Number(user.questionUsage[q.id]||0)+1;user.answerHistory.push(q.id);}user.answerHistory=user.answerHistory.slice(-8);const avgDiff=chosen.reduce((s,q)=>s+Number(q.difficulty||1),0)/chosen.length;const duration=Math.max(60,n*60);return{id:\`mission_\${Date.now()}_\${Math.random().toString(36).slice(2,8)}\`,jobId,started_at:new Date().toISOString(),duration_seconds:duration,questionRefs:chosen.map(q=>q.id),questions:chosen.map(q=>({id:q.id,text:q.text,options:q.options})),rewardXp:Math.max(20,Math.floor((Number(cfg.xpPerMission)||50)*avgDiff)),rewardMoney:Math.max(50,Math.floor((Number(cfg.moneyPerMission)||50)*avgDiff)),answers:[],status:'active'}};\n\napp.post('/api/register'`);
    source=source.replace(/const normalizeMissionUser=.*?const findQuestionById=qid=>/s,'const findQuestionById=qid=>');
    source=source.replace(/const final=m\.answers\.filter\(v=>v!==undefined\)\.length>=m\.questions\.length;/g,'const final=m.answers.filter(v=>v!==undefined).length>=m.questions.length;const earnedMoney=Math.floor((m.rewardMoney||0)*((m.correctCount||0)/Math.max(1,m.questions.length)));const earnedXp=final?Math.floor((m.rewardXp||0)*((m.correctCount||0)/Math.max(1,m.questions.length))):0;');
    source=source.replace(/if\(answer===q\.correct\)req\.user\.xp=\(req\.user\.xp\|\|0\)\+Math\.max\(1,Math\.floor\(\(m\.rewardXp\|\|20\)\/m\.questions\.length\)\);/g,'');
    source=source.replace(/m\.status='completed';m\.createdAt=new Date\(\);registerMissionUse\(req\.user\);/g,"m.status='completed';m.createdAt=new Date();if(!req.user.professionalXpByJob||typeof req.user.professionalXpByJob!=='object')req.user.professionalXpByJob={};const professionalJobId=req.user.jobId||m.jobId;if(!Number.isFinite(Number(req.user.professionalXpByJob[professionalJobId])))req.user.professionalXpByJob[professionalJobId]=0;req.user.professionalXpByJob[professionalJobId]+=earnedXp;registerMissionUse(req.user);");
    source=source.replace(/req\.user\.money=\(req\.user\.money\|\|0\)\+\(m\.rewardMoney\|\|0\);/g,'req.user.money=(req.user.money||0)+earnedMoney;');
    source=source.replace(/moneyGiven:final\?m\.rewardMoney\|\|0:0/g,'moneyGiven:final?earnedMoney:0');
    source=source.replace(/xpGiven:final\?m\.rewardXp\|\|0:0/g,'xpGiven:final?earnedXp:0');
    source=source.replace(/message:final\?\'Missão concluída!\':\(answer===q\.correct\?\'Resposta correta!\':\'Resposta incorreta!\'\)/g,"message:answer===q.correct?'Resposta correta!':'Resposta incorreta!'");
    source=source.replace(/app\.get\('\/api\/me',\(req,res\)=>res\.json\(\{user:\{name:req\.user\.name,username:req\.user\.username,money:req\.user\.money,level:req\.user\.level,xp:req\.user\.xp,jobName:req\.user\.jobName,life:req\.user\.life,hunger:req\.user\.hunger,hydration:req\.user\.hydration,energy:req\.user\.energy\},isMayor:req\.user\.isMayor\}\)\);/,"app.get('/api/me',(req,res)=>res.json({user:{name:req.user.name,username:req.user.username,money:req.user.money,level:req.user.level,xp:req.user.xp,jobId:req.user.jobId,jobName:req.user.jobName,professionalXpByJob:req.user.professionalXpByJob||{},professionalXp:Number((req.user.professionalXpByJob||{})[req.user.jobId]||0),life:req.user.life,hunger:req.user.hunger,hydration:req.user.hydration,energy:req.user.energy},isMayor:req.user.isMayor}));");
    source=source.replace("app.get('/api/jobs',(req,res)=>res.json({jobs,currentJob:req.user.jobId,xp:req.user.xp}));","app.get('/api/jobs',(req,res)=>res.json({jobs,currentJob:req.user.jobId,xp:req.user.xp,professionalXpByJob:req.user.professionalXpByJob||{},professionalXp:Number((req.user.professionalXpByJob||{})[req.user.jobId]||0)}));");
    return module._compile(source,filename);
  }
  return originalLoader(module,filename);
};
