(function(){
'use strict';
const EXAMS={sangue:'Exame de sangue',urina:'Exame de urina',glicose:'Glicose',pressao:'Pressão arterial',temperatura:'Temperatura',colesterol:'Colesterol',vitaminas:'Vitaminas'};
const STEPS=[['reception','Recepção'],['triage','Triagem'],['consultation','Consulta'],['evaluation','Avaliação'],['exam_waiting','Exame'],['results_review','Resultado'],['treatment','Tratamento'],['completed','Fim']];
window.hospitalPageV2=async function(box){try{const d=await api('/api/hospital');renderHospital(box,d);}catch(e){box.innerHTML='<div class="empty"><h3>Hospital</h3><p>'+esc(e.message)+'</p></div>';}};
function stageLabel(s){return ({reception:'Recepção',triage:'Triagem',consultation:'Consulta',evaluation:'Avaliação',exam_waiting:'Aguardando resultado',results_review:'Revisão do resultado',treatment:'Tratamento',completed:'Atendimento concluído'})[s]||'Recepção';}
function stepIndex(s){const i=STEPS.findIndex(x=>x[0]===s);return i<0?0:i;}
function renderHospital(box,d){
 const v=d.health||{},visit=d.visit,exams=d.exams||[],stage=visit?.stage||'reception',conv=d.conversation||{},pending=exams.filter(e=>e.status==='pending'&&e.visitId===visit?.id),ready=exams.filter(e=>['ready','reviewed'].includes(e.status)&&e.visitId===visit?.id),exam=visit?.orderedExamId?exams.find(e=>e.id===visit.orderedExamId):null,idx=stepIndex(stage);
 const room=stage==='reception'?'reception':stage==='triage'?'triage':stage==='consultation'?'office':stage==='evaluation'?'evaluation':stage==='exam_waiting'?'lab':stage==='results_review'?'results':'pharmacy';
 const speaker=conv.speaker==='nurse'?'Enfermeiro':'Médico';
 let actions='';
 if(!visit) actions='<button class="primary hosp-main-btn" onclick="hospitalDo(\'checkin\')"><b>Solicitar atendimento</b><small>Registrar sua chegada na recepção</small></button>';
 else if(stage==='triage') actions='<button class="primary hosp-main-btn" onclick="hospitalDo(\'triage\')"><b>Passar pela triagem</b><small>O enfermeiro vai verificar seus sinais</small></button>';
 else if(stage==='consultation') actions=dialogActions(d);
 else if(stage==='evaluation') actions='<button class="primary hosp-main-btn" onclick="hospitalDo(\'evaluation\')"><b>Iniciar avaliação</b><small>O médico vai fazer a avaliação do atendimento</small></button>';
 else if(stage==='exam_waiting') actions='<div class="hosp-wait-card"><div class="lab-loader big"></div><div><b>'+esc(exam?.name||'Exame solicitado')+'</b><small>O laboratório está processando o resultado.</small><strong>'+remaining(exam?.readyAt)+'</strong></div></div><button onclick="hospitalDo(\'refresh\')" class="ghost"><b>Verificar resultado</b><small>Atualizar o atendimento</small></button>';
 else if(stage==='results_review') actions='<button class="primary hosp-main-btn" onclick="hospitalReview(\''+(exam?.id||'')+'\')"><b>Voltar ao consultório</b><small>O médico vai analisar o resultado com você</small></button>';
 else if(stage==='treatment') actions='<div class="prescription-preview"><span>FOLHA DO HOSPITAL SOROKIBA</span><b>'+esc(visit?.treatment?.title||'Plano de atendimento')+'</b><p>'+esc(visit?.treatment?.text||'O médico registrou as orientações do atendimento.')+'</p></div><button class="primary hosp-main-btn" onclick="hospitalDo(\'discharge\')"><b>Finalizar atendimento</b><small>Guardar o registro e sair do Hospital</small></button>';
 else if(stage==='completed') actions='<div class="hosp-complete"><b>Atendimento concluído</b><small>Seu registro foi salvo no histórico.</small></div>';
 box.innerHTML='<div class="hosp">'+
 '<div class="hosp-header"><div><span class="hosp-kicker">CENTRO MÉDICO</span><h1>Hospital Sorokiba</h1><p>Um atendimento completo, passo a passo.</p></div><div class="hosp-status"><i></i><b>'+stageLabel(stage)+'</b><small>'+(pending.length?'Resultado em processamento':(exam?'Exame: '+esc(exam.name):'Atendimento ativo'))+'</small></div></div>'+scene(room,speaker,stage,conv)+
 '<div class="hosp-steps">'+STEPS.map((s,i)=>'<div class="'+(i<idx?'done ':i===idx?'active ':'')+'"><b>'+(i<idx?'✓':i+1)+'</b><span>'+s[1]+'</span></div>').join('')+'</div>'+ 
 '<div class="hosp-grid"><section class="hosp-panel"><div class="hosp-panel-head"><div><small>ATENDIMENTO</small><h2>'+stageLabel(stage)+'</h2></div><span class="hosp-area">Etapa '+(idx+1)+' de '+STEPS.length+'</span></div>'+vitals(v)+ '<div class="hosp-dialogue">'+dialogueText(stage,conv,exam,visit)+'</div><div class="hosp-actions">'+actions+'</div></section>'+ 
 '<section class="hosp-panel"><div class="hosp-panel-head"><div><small>REGISTRO</small><h2>Resumo do atendimento</h2></div></div><div class="hosp-record">'+record(visit,exam,ready)+'</div></section></div></div>';
 if(stage==='exam_waiting'){clearInterval(window.__hospitalRefresh);window.__hospitalRefresh=setInterval(()=>{if(currentPage==='hospital')hospitalPageV2(document.getElementById('content'));else clearInterval(window.__hospitalRefresh)},15000);}
}
function scene(room,speaker,stage,conv){
 let chars='';
 let props='<div class="hosp-ceiling"></div><div class="hosp-window"><span></span><span></span><span></span></div>';
 if(stage==='reception'){
   chars='<div class="hosp-receptionist"><div class="reception-head"></div><div class="reception-body"></div><div class="reception-arm"></div></div><div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
   props+='<div class="hosp-reception-desk"></div><div class="hosp-computer"><i></i><b></b></div>';
 }else if(stage==='triage'){
   chars='<div class="hosp-npc nurse-npc scene-nurse"><div class="npc-head"></div><div class="npc-body"></div><div class="npc-arm"></div></div><div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
   props+='<div class="hosp-triage-bed"></div><div class="hosp-monitor"><div class="monitor-screen"><span></span><b>♥</b><em></em></div><div class="monitor-base"></div></div>';
 }else if(stage==='consultation'){
   chars='<div class="hosp-doctor"><div class="doctor-hair"></div><div class="doctor-head"><i></i><i></i></div><div class="doctor-body"><b>+</b></div><div class="doctor-arm"></div><div class="doctor-clipboard"></div></div><div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
   props+='<div class="hosp-desk"></div><div class="hosp-chair scene-chair"></div><div class="hosp-monitor"><div class="monitor-screen"><span></span><b>♥</b><em></em></div><div class="monitor-base"></div></div>';
 }else if(stage==='evaluation'){
   chars='<div class="hosp-doctor"><div class="doctor-hair"></div><div class="doctor-head"><i></i><i></i></div><div class="doctor-body"><b>+</b></div><div class="doctor-arm"></div><div class="doctor-clipboard"></div></div><div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
   props+='<div class="hosp-exam-bed"></div><div class="hosp-exam-lamp"></div><div class="hosp-monitor"><div class="monitor-screen"><span></span><b>♥</b><em></em></div><div class="monitor-base"></div></div>';
 }else if(stage==='exam_waiting'){
   chars='<div class="hosp-lab-tech"><div class="lab-head"></div><div class="lab-body"></div><div class="lab-arm"></div></div>';
   props+='<div class="hosp-lab-table"></div><div class="hosp-lab-machine"><i></i><b></b></div><div class="lab-loader big"></div>';
 }else if(stage==='results_review'){
   chars='<div class="hosp-doctor"><div class="doctor-hair"></div><div class="doctor-head"><i></i><i></i></div><div class="doctor-body"><b>+</b></div><div class="doctor-arm"></div><div class="doctor-clipboard"></div></div><div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
   props+='<div class="hosp-desk"></div><div class="hosp-result-paper"></div>';
 }else if(stage==='treatment'){
   chars='<div class="hosp-doctor"><div class="doctor-hair"></div><div class="doctor-head"><i></i><i></i></div><div class="doctor-body"><b>+</b></div><div class="doctor-arm"></div></div>';
   props+='<div class="hosp-desk"></div><div class="hosp-printer"><i></i><b></b></div><div class="hosp-prescription"></div>';
 }else{
   chars='<div class="hosp-patient scene-patient"><div class="patient-head"></div><div class="patient-body"></div></div>';
 }
 return '<div class="hosp-building room-'+room+' stage-'+stage+'">'+props+chars+'<div class="hosp-lamp l1"></div><div class="hosp-lamp l2"></div><div class="hosp-scene-copy"><small>'+esc(stageLabel(stage).toUpperCase())+'</small><strong>'+speaker+'</strong><span class="hosp-dots"><i></i><i></i><i></i></span><p>'+esc(sceneText(stage,conv))+'</p></div></div>';
}
function sceneText(s,c){return ({reception:'A recepção está pronta para registrar sua chegada.',triage:'O enfermeiro confere os sinais do personagem.',consultation:'O médico conversa com você antes de decidir o próximo passo.',evaluation:'O médico faz uma avaliação simples do personagem.',exam_waiting:'O laboratório está processando o exame solicitado.',results_review:'O médico recebeu o resultado e está revisando a ficha.',treatment:'A receita está sendo preparada na impressora.',completed:'Atendimento encerrado.'})[s]||'Atendimento em andamento.';}
function vitals(v){return '<div class="hosp-vitals"><div><small>VIDA</small><b>'+v.life+'</b></div><div><small>FOME</small><b>'+v.hunger+'</b></div><div><small>HIDRATAÇÃO</small><b>'+v.hydration+'</b></div><div><small>ENERGIA</small><b>'+v.energy+'</b></div></div>';}
function dialogActions(d){const c=d.conversation||{};if(c.question==='symptoms')return '<button onclick="hospitalTalk(\'symptom\',\'cansaco\')"><b>Cansaço</b><small>Estou me sentindo sem energia.</small></button><button onclick="hospitalTalk(\'symptom\',\'dor\')"><b>Desconforto</b><small>Estou sentindo um desconforto.</small></button><button onclick="hospitalTalk(\'symptom\',\'tontura\')"><b>Tontura</b><small>Estou me sentindo estranho.</small></button><button onclick="hospitalTalk(\'symptom\',\'nada\')"><b>Nada específico</b><small>Vim fazer uma avaliação.</small></button>';if(c.question==='duration')return '<button onclick="hospitalTalk(\'duration\',\'hoje\')"><b>Começou hoje</b></button><button onclick="hospitalTalk(\'duration\',\'dias\')"><b>Há alguns dias</b></button><button onclick="hospitalTalk(\'duration\',\'tempo\')"><b>Já faz algum tempo</b></button>';if(c.question==='other')return '<button onclick="hospitalTalk(\'other\',\'sim\')"><b>Sim, tenho outra coisa para contar</b></button><button onclick="hospitalTalk(\'other\',\'nao\')"><b>Não, é só isso</b></button>';return '<button class="primary" onclick="hospitalTalk(\'start\',\'\')"><b>Começar conversa com o médico</b><small>Responder algumas perguntas</small></button>';}
function dialogueText(stage,c,exam,visit){if(stage==='consultation')return '<div class="speech"><b>'+esc(c.speaker==='nurse'?'Enfermeiro':'Médico')+':</b><span>'+esc(c.text||'Olá. Quero entender como você está se sentindo antes de continuarmos.')+'</span></div>';if(stage==='exam_waiting')return '<div class="speech"><b>Laboratório:</b><span>O resultado de '+esc(exam?.name||'seu exame')+' ainda está sendo processado.</span></div>';if(stage==='results_review')return '<div class="speech"><b>Médico:</b><span>O resultado ficou pronto. Vamos revisar a ficha juntos.</span></div>';if(stage==='treatment')return '<div class="speech"><b>Médico:</b><span>'+esc(visit?.treatment?.doctorMessage||'O atendimento foi concluído e a folha do Hospital foi preparada.')+'</span></div>';return '<div class="speech"><b>'+esc(c.speaker==='nurse'?'Enfermeiro':'Médico')+':</b><span>'+esc(c.text||'Vamos seguir para a próxima etapa do atendimento.')+'</span></div>';}
function record(visit,exam,ready){if(!visit)return '<div class="record-empty">Nenhum atendimento ativo. Vá à recepção para começar.</div>';let s='<div><small>PRIORIDADE</small><b>'+((visit.urgent)?'Prioritário':'Normal')+'</b></div><div><small>SINTOMAS REGISTRADOS</small><b>'+((visit.symptoms||[]).length?visit.symptoms.join(', '):'Ainda não registrados')+'</b></div>';if(exam)s+='<div><small>EXAME</small><b>'+esc(exam.name)+'</b><span>'+((exam.status==='pending')?'Aguardando resultado':exam.status==='reviewed'?'Resultado revisado':'Resultado pronto')+'</span></div>';if(ready.length)s+='<div><small>RESULTADO DISPONÍVEL</small><b>'+esc(ready[0].name)+'</b></div>';return s;}
function remaining(iso){if(!iso)return'Em processamento';const n=Date.parse(iso)-Date.now();if(n<=0)return'Pronto para revisão';const m=Math.floor(n/60000);return m<1?'menos de 1 min':m+' min';}
window.hospitalDo=async function(action){try{const d=await post('/api/hospital/'+action,{});const md=await api('/api/me');me=md.user;updateHUD();toast(d.message||'Concluído');renderHospital($('#content'),d);}catch(e){toast(e.message,'error');}};
window.hospitalTalk=async function(intent,choice){try{const d=await post('/api/hospital/talk',{intent,choice});renderHospital($('#content'),d);}catch(e){toast(e.message,'error');}};
window.hospitalReview=async function(id){try{const d=await post('/api/hospital/exams/'+encodeURIComponent(id)+'/review',{});renderHospital($('#content'),d);}catch(e){toast(e.message,'error');}};
})();