const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const path = require('path');
const db = require('./db');

const app = express();
app.use(cors());
app.use(bodyParser.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname)));

const fs = require('fs');
const DATA_DIR = path.join(__dirname, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR);

let users = {};
let city = { population:0, economy:8500, infrastructure:65, quality:72, taxRate:15, treasury:50000, news:[], events:[], proposals:[], missionRewards:{}, companies:[] };

const ensureCompanyData=()=>{if(!city||typeof city!=='object')city={};if(!Array.isArray(city.companies))city.companies=[];city.companies.forEach(c=>{if(!Array.isArray(c.products))c.products=[];if(!Number.isFinite(Number(c.balance)))c.balance=0})};
const processCompanyFees=()=>{
  if(!city||!Array.isArray(city.companies))return;
  let changed=false;
  const now=Date.now(),week=7*24*60*60*1000;
  city.companies.forEach(c=>{
    if(!c.nextFeeAt)c.nextFeeAt=new Date(now+week).toISOString();
    while(new Date(c.nextFeeAt).getTime()<=now){
      const owner=users[c.ownerUsername],fee=250;
      let paid=0;
      if(Number(c.balance||0)>=fee){c.balance-=fee;paid=fee}
      else if(owner&&Number(owner.money||0)>=fee){owner.money-=fee;paid=fee}
      if(paid){
        city.treasury=Number(city.treasury||0)+paid;
        c.lastFee={date:new Date().toISOString(),amount:paid,status:'paid'};
        c.nextFeeAt=new Date(new Date(c.nextFeeAt).getTime()+week).toISOString();
      }else{
        c.lastFee={date:new Date().toISOString(),amount:fee,status:'pending'};
        c.feeDebt=(Number(c.feeDebt)||0)+fee;
        c.nextFeeAt=new Date(new Date(c.nextFeeAt).getTime()+week).toISOString();
      }
      changed=true;
    }
  });
  if(changed)saveData();
};
const loadData = async () => {
  try {
    users = (await db.get('users')) || users;
    city = (await db.get('city')) || city;
    const qb = await db.get('questionBank');
    if (qb) Object.assign(questionBank, qb);
    ensureCompanyData();
  } catch(e){ console.error('Falha ao carregar do Postgres',e); ensureCompanyData(); }
};
let saveTimer=null;
const saveData=()=>{if(saveTimer)return;saveTimer=setTimeout(async()=>{saveTimer=null;try{await db.set('users',users);await db.set('city',city);await db.set('questionBank',questionBank)}catch(e){console.error('Falha ao salvar no Postgres',e)}},500)};
setInterval(()=>processCompanyFees(),60*60*1000);
let tokenCounter=0;
const generateToken=()=>`token_${++tokenCounter}_${Date.now()}`;

const jobs=[
{id:'estudante',name:'Estudante',salary:100,xpRequired:0,task:'Estude para o futuro',icon:'🎓'},
{id:'entregador',name:'Entregador de Food',salary:250,xpRequired:200,task:'Faça entregas pela cidade',icon:'📦'},
{id:'mecanico',name:'Mecânico',salary:400,xpRequired:400,task:'Conserte veículos e máquinas',icon:'🔧'},
{id:'professor',name:'Professor',salary:500,xpRequired:600,task:'Ensine as próximas gerações',icon:'📚'},
{id:'policial',name:'Policial',salary:600,xpRequired:700,task:'Proteja a cidade',icon:'🛡️'},
{id:'investigador',name:'Investigador',salary:700,xpRequired:900,task:'Investigue crimes e mistérios',icon:'🕵️'},
{id:'advogado',name:'Advogado',salary:750,xpRequired:1000,task:'Defenda clientes',icon:'⚖️'},
{id:'engenheiro',name:'Engenheiro',salary:850,xpRequired:1100,task:'Construa infraestrutura',icon:'🏗️'},
{id:'medico',name:'Médico',salary:950,xpRequired:1300,task:'Trate dos enfermos',icon:'⚕️'},
{id:'juiz',name:'Juiz do Tribunal',salary:1200,xpRequired:1800,task:'Julgue casos importantes',icon:'🏛️'}];

const questionBank={
 estudante:[{id:'e1',text:'Qual é a capital do Brasil?',options:['São Paulo','Brasília','Rio de Janeiro','Salvador'],correct:1,difficulty:1},{id:'e2',text:'2+2 é?',options:['3','4','5','22'],correct:1,difficulty:1}],
 medico:[{id:'m1',text:'Febre, dor de garganta e tosse: qual a causa mais provável?',options:['Dengue','Gripe','Diabetes','Hipertensão'],correct:1,difficulty:1},{id:'m2',text:'Qual exame é usado para verificar fraturas ósseas?',options:['Ressonância','Ultrassom','Raio-X','ECG'],correct:2,difficulty:2}],
 policial:[{id:'p1',text:'Ao abordar um suspeito, o policial deve:',options:['Ignorar','Insistir sem backup','Garantir segurança e chamar apoio','Filmar com celular'],correct:2,difficulty:1}],
 entregador:[{id:'d1',text:'Melhor prática para entregas seguras:',options:['Dirigir rápido','Ignorar endereços','Conferir pedido antes de sair','Levar menos itens'],correct:2,difficulty:1}],
 generic:[{id:'g1',text:'Qual é a cor do céu em um dia claro?',options:['Azul','Verde','Vermelho','Amarelo'],correct:0,difficulty:1}]};
try{const qfile=path.join(DATA_DIR,'questionBank.json');if(fs.existsSync(qfile))Object.assign(questionBank,JSON.parse(fs.readFileSync(qfile,'utf8')))}catch(e){console.error('Failed loading questionBank.json',e)}
try{if(!city.missionRewards)city.missionRewards={};jobs.forEach(j=>{if(!city.missionRewards[j.id]){const money=Math.max(50,Math.floor(j.salary*.15));const xp=Math.max(20,Math.floor(j.salary*.08));const questions=j.xpRequired>=1000?3:2;city.missionRewards[j.id]={moneyPerMission:money,xpPerMission:xp,questionsPerMission:questions}}})}catch(e){console.error('Failed initializing missionRewards',e)}

const shopItems=[
{id:1,name:'Pão Integral',price:10,hunger:30,icon:'🍞',description:'Um pão delicioso'},
{id:2,name:'Água',price:5,hydration:50,icon:'💧',description:'Água fresca'},
{id:3,name:'Maçã',price:8,hunger:20,energy:10,icon:'🍎',description:'Maçã vermelha'},
{id:4,name:'Refrigerante',price:7,hydration:20,energy:15,icon:'🥤',description:'Refrigerante gelado'},
{id:5,name:'Pizza',price:20,hunger:50,icon:'🍕',description:'Pizza quentinha'},
{id:6,name:'Café',price:6,energy:30,icon:'☕',description:'Café coado'}];
const hospitalServices=[{id:1,name:'Consulta Rápida',price:100,life:30},{id:2,name:'Atendimento Completo',price:300,life:70},{id:3,name:'Cirurgia',price:800,life:100}];

const defaultCharacter=()=>({gender:'masculino',skin:'#f1c27d',hair:'#2b2118',hairStyle:'curto',shirt:'#4f6cff',pants:'#273449',shoes:'#151a22',bodyType:'normal',eyeStyle:'normal',browStyle:'normal',mouthStyle:'normal',
  earStyle:'normal',noseStyle:'normal',accessories:[],held:null});
const normalizeCharacter=c=>{const d=defaultCharacter(),s=c&&typeof c==='object'?c:{};const color=(v,f)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):f;const genders=['masculino','feminino'];const hairs=['curto','medio','longo','cacheado','crespo','coque','raspado','moicano','franja','lateral'];const bodies=['magro','normal','forte'];const eyes=['normal','grande','fechado','estreito','brilhante'];const brows=['normal','reto','arqueada','forte','preocupada'];const mouths=['normal','sorriso','serio','aberta','surpreso','triste'];
  const ears=['normal','pequena','redonda','pontuda'];const noses=['normal','fino','arredondado','arrebitado'];return{gender:genders.includes(s.gender)?s.gender:d.gender,skin:color(s.skin,d.skin),hair:color(s.hair,d.hair),hairStyle:hairs.includes(s.hairStyle)?s.hairStyle:d.hairStyle,shirt:color(s.shirt,d.shirt),pants:color(s.pants,d.pants),shoes:color(s.shoes,d.shoes),bodyType:bodies.includes(s.bodyType)?s.bodyType:d.bodyType,eyeStyle:eyes.includes(s.eyeStyle)?s.eyeStyle:d.eyeStyle,browStyle:brows.includes(s.browStyle)?s.browStyle:d.browStyle,mouthStyle:mouths.includes(s.mouthStyle)?s.mouthStyle:d.mouthStyle,noseStyle:noses.includes(s.noseStyle)?s.noseStyle:d.noseStyle,earStyle:ears.includes(s.earStyle)?s.earStyle:d.earStyle,accessories:Array.isArray(s.accessories)?s.accessories.map(x=>String(x).slice(0,80)).slice(0,8):[],held:s.held?String(s.held).slice(0,80):null}};
const findQuestionById=qid=>{for(const k of Object.keys(questionBank)){const q=questionBank[k].find(x=>x.id===qid);if(q)return q}return null};
const getMissionState=user=>{const now=Date.now();user.missionBatchCount=Number.isFinite(Number(user.missionBatchCount))?Number(user.missionBatchCount):0;user.missionCooldownUntil=user.missionCooldownUntil||null;if(user.missionCooldownUntil){const cooldown=new Date(user.missionCooldownUntil).getTime();if(Number.isFinite(cooldown)&&cooldown<=now){user.missionCooldownUntil=null;user.missionBatchCount=0}}return{batchCount:user.missionBatchCount,remaining:Math.max(0,2-user.missionBatchCount),cooldownUntil:user.missionCooldownUntil}};
const startCooldownIfNeeded=user=>{if(Number(user.missionBatchCount)>=2)user.missionCooldownUntil=new Date(Date.now()+30*60*1000).toISOString()};
const createMission=(jobId,username)=>{const cfg=(city.missionRewards&&city.missionRewards[jobId])||{questionsPerMission:2,xpPerMission:50,moneyPerMission:50};const duration=Math.max(60,cfg.questionsPerMission*60);const jobQuestions=(questionBank[jobId]&&questionBank[jobId].length?questionBank[jobId]:questionBank.generic).slice();const answered=(users[username]&&users[username].answeredQuestions)||[];const questionUsage=(users[username]&&users[username].questionUsage)||{};let pool=jobQuestions.filter(q=>Number(questionUsage[q.id]||0)<2&&!answered.includes(q.id));if(pool.length<(cfg.questionsPerMission||2)){const minUse=Math.min(...jobQuestions.map(q=>Number(questionUsage[q.id]||0)));pool=jobQuestions.filter(q=>Number(questionUsage[q.id]||0)===minUse&&!answered.includes(q.id));}if(pool.length<(cfg.questionsPerMission||2))pool=jobQuestions.slice();if(!pool.length)return null;const n=Math.min(cfg.questionsPerMission||2,pool.length),chosen=[],poolCopy=pool.slice();for(let i=0;i<n;i++)chosen.push(poolCopy.splice(Math.floor(Math.random()*poolCopy.length),1)[0]);if(users[username]){users[username].questionUsage=users[username].questionUsage||{};chosen.forEach(q=>{users[username].questionUsage[q.id]=Number(users[username].questionUsage[q.id]||0)+1})}const avgDiff=chosen.reduce((s,q)=>s+(q.difficulty||1),0)/chosen.length;return{id:`mission_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,jobId,started_at:new Date().toISOString(),duration_seconds:duration,questionRefs:chosen.map(q=>q.id),questions:chosen.map(q=>({id:q.id,text:q.text,options:q.options})),rewardXp:Math.max(20,Math.floor((cfg.xpPerMission||50)*avgDiff)),rewardMoney:Math.max(50,Math.floor((cfg.moneyPerMission||50)*avgDiff)),answers:[],status:'active'}};

app.post('/api/register',(req,res)=>{const{name,username,password,recoveryCode}=req.body;if(!name||!username||!password||!recoveryCode)return res.status(400).json({error:'Preencha todos os campos'});if(users[username])return res.status(400).json({error:'Usuário já existe'});const isMayor=Object.keys(users).length===0;users[username]=createUser(name,username,password,isMayor,recoveryCode);if(!users[username].countedInPopulation){city.population=Number(city.population||0)+1;users[username].countedInPopulation=true}users[username].token=generateToken();saveData();res.json({message:isMayor?'Conta criada! Você é o prefeito.':'Conta criada com sucesso!',token:users[username].token,user:users[username]})});
app.post('/api/login',(req,res)=>{const{username,password}=req.body,user=users[username];if(!user||user.password!==password)return res.status(401).json({error:'Usuário ou senha incorretos'});user.token=generateToken();if(!user.countedInPopulation){city.population=Number(city.population||0)+1;user.countedInPopulation=true}saveData();res.json({message:'Login realizado!',token:user.token,user})});
app.post('/api/recover-password',async(req,res)=>{try{const{username,name,recoveryCode,newPassword}=req.body||{};if(!username||!name||!recoveryCode||!newPassword)return res.status(400).json({error:'Preencha todos os campos'});if(String(newPassword).length<6)return res.status(400).json({error:'A nova senha deve ter no mínimo 6 caracteres'});const user=users[username];if(!user||user.name!==name||user.recoveryCode!==recoveryCode)return res.status(401).json({error:'Dados de recuperação incorretos'});user.password=newPassword;user.token=null;saveData();res.json({message:'Senha alterada com sucesso! Você já pode entrar novamente.'})}catch(e){console.error('Falha na recuperação de senha',e);res.status(500).json({error:'Não foi possível recuperar a senha agora.'})}});
const auth=(req,res,next)=>{const token=req.headers.authorization?.replace('Bearer ','');const user=Object.values(users).find(u=>u.token===token);if(!user)return res.status(401).json({error:'Não autenticado'});req.user=user;req.username=user.username;next()};
app.use('/api',(req,res,next)=>{if(['/api/register','/api/login','/api/recover-password'].includes(req.originalUrl.split('?')[0]))return next();auth(req,res,next)});
const requireActiveSession=(req,res,next)=>{req.user.lastActiveAt=Date.now();next()};
app.post('/api/me/activity',requireActiveSession,(req,res)=>{const activeSeconds=Math.max(0,Math.min(30,Number(req.body?.activeSeconds)||0));req.user.activeNeedSeconds=Math.max(0,Number(req.user.activeNeedSeconds)||0)+activeSeconds;const minutes=Math.floor(req.user.activeNeedSeconds/60);if(minutes>0){req.user.activeNeedSeconds-=minutes*60;req.user.hunger=Math.max(0,Number(req.user.hunger??100)-minutes);req.user.hydration=Math.max(0,Number(req.user.hydration??100)-minutes);req.user.energy=Math.max(0,Number(req.user.energy??100)-minutes);if(req.user.hunger<20)req.user.life=Math.max(0,Number(req.user.life??100)-(minutes*2))}saveData();res.json({hunger:req.user.hunger,hydration:req.user.hydration,energy:req.user.energy,life:req.user.life})});
app.post('/api/me/offline',(req,res)=>{req.user.lastActiveAt=0;saveData();res.json({ok:true})});
app.get('/api/me',(req,res)=>{req.user.character=normalizeCharacter(req.user.character);res.json({user:{name:req.user.name,username:req.user.username,money:req.user.money,level:req.user.level,xp:req.user.xp,jobName:req.user.jobName,life:req.user.life,hunger:req.user.hunger,hydration:req.user.hydration,energy:req.user.energy,character:req.user.character},isMayor:req.user.isMayor})});
app.put('/api/me/character',(req,res)=>{const next=normalizeCharacter(req.body?.character);ensureCompanyData();const owned=req.user.companyInventory||{};const valid=new Set();city.companies.forEach(c=>c.products.forEach(p=>{if(Number(owned[p.id]||0)>0&&['equipamento','tecnologia','decoracao'].includes(p.type))valid.add(p.id)}));next.accessories=next.accessories.filter(id=>valid.has(id));if(next.held&&!valid.has(next.held))next.held=null;req.user.character=next;saveData();res.json({message:'Personagem atualizado!',character:req.user.character})});
app.get('/api/city',(req,res)=>res.json(city));
app.get('/api/jobs',(req,res)=>res.json({jobs,currentJob:req.user.jobId,xp:req.user.xp}));
app.post('/api/jobs/select',(req,res)=>{const j=jobs.find(x=>x.id===req.body.jobId);if(!j)return res.status(404).json({error:'Profissão não encontrada'});if(req.user.xp<j.xpRequired)return res.status(403).json({error:'XP insuficiente'});req.user.jobId=j.id;req.user.jobName=j.name;saveData();res.json({message:`Profissão escolhida: ${j.name}`,user:req.user})});
const companyProductTypes={consumivel:'Consumível',equipamento:'Equipamento',tecnologia:'Tecnologia',veiculo:'Veículo',decoracao:'Decoração'};
const companyId=()=> 'company_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const productId=()=> 'prod_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
const ct=(v,m)=>String(v??'').trim().slice(0,m);
const effects=v=>{const s=v&&typeof v==='object'?v:{},o={};['hunger','hydration','energy','life'].forEach(k=>{const n=Number(s[k]||0);if(Number.isFinite(n)&&n)o[k]=Math.max(-100,Math.min(100,Math.round(n)))});return o};
const vehicleCustomization=v=>{const s=v&&typeof v==='object'?v:{};const pick=(key,fallback)=>{const x=String(s[key]??fallback).trim();return /^#[0-9a-f]{6}$/i.test(x)?x:fallback};return{bodyColor:pick('bodyColor','#dfe6ee'),secondaryColor:pick('secondaryColor','#273449'),wheelColor:pick('wheelColor','#151a22'),windowColor:pick('windowColor','#7fc8e8'),neonColor:pick('neonColor','#7c5cff'),plateColor:pick('plateColor','#f2f2f2'),wheels:ct(s.wheels,30)||'Esportivas',windows:ct(s.windows,30)||'Originais',spoiler:!!s.spoiler,neon:!!s.neon,tint:Math.max(0,Math.min(100,Math.round(Number(s.tint)||0)))}};
const productInput=b=>{const type=String(b?.type||'consumivel'),name=ct(b?.name,80),description=ct(b?.description,300),price=Number(b?.price),image=typeof b?.image==='string'?b.image.trim():'';const emoji=ct(b?.emoji,8)||'📦';if(!companyProductTypes[type])return{error:'Tipo de produto inválido.'};if(!name)return{error:'Informe o nome do produto.'};if(!Number.isFinite(price)||price<=0||price>1000000)return{error:'Preço inválido.'};if(image.length>550000)return{error:'A foto é grande demais.'};if(image&&!/^data:image\/(png|jpeg|jpg|webp|gif);base64,/i.test(image)&&!/^https?:\/\//i.test(image))return{error:'Foto inválida.'};return{product:{id:productId(),name,description,price:Math.round(price*100)/100,type,effects:type==='consumivel'?effects(b?.effects):{},image,emoji,vehicleCustomization:type==='veiculo'?vehicleCustomization(b?.vehicleCustomization):null,createdAt:new Date().toISOString()}}};
const validCompanyImage=v=>{const image=typeof v==='string'?v.trim():'';if(!image)return '';if(image.length>550000)return null;if(!/^data:image\/(png|jpeg|jpg|webp|gif);base64,/i.test(image)&&!/^https?:\/\//i.test(image))return null;return image};
const publicCompany=c=>({id:c.id,name:c.name,description:c.description,companyImage:c.companyImage||'',ownerUsername:c.ownerUsername,ownerName:c.ownerName,featured:!!c.featured,createdAt:c.createdAt,productCount:c.products.length,products:c.products,totalSales:c.totalSales||0,salesCount:c.salesCount||0,level:c.level||1,xp:c.xp||0});
app.get('/api/my-companies',(req,res)=>{ensureCompanyData();processCompanyFees();const mine=city.companies.filter(c=>c.ownerUsername===req.username).map(c=>({...publicCompany(c),balance:c.balance||0,totalSales:c.totalSales||0,salesCount:c.salesCount||0,level:c.level||1,xp:c.xp||0,nextFeeAt:c.nextFeeAt||null,weeklyFee:250}));res.json({companies:mine})});
app.post('/api/companies/:id/vehicle-sightings',(req,res)=>res.status(400).json({error:'Veículos são registrados automaticamente nas saudações.'}));
app.get('/api/company-sales',(req,res)=>{ensureCompanyData();processCompanyFees();const c=city.companies.find(x=>x.id===req.query.companyId&&x.ownerUsername===req.username);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});res.json({sales:c.sales||[],balance:c.balance||0,totalSales:c.totalSales||0,salesCount:c.salesCount||0,level:c.level||1,xp:c.xp||0,weeklyFee:250,nextFeeAt:c.nextFeeAt||null})});
app.get('/api/companies',(req,res)=>{ensureCompanyData();const q=ct(req.query?.search,80).toLowerCase();let list=city.companies.map(publicCompany);if(q)list=list.filter(c=>c.name.toLowerCase().includes(q)||c.description.toLowerCase().includes(q)||c.products.some(p=>p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q)));const featured=list.filter(c=>c.featured).slice(0,6);const recent=list.filter(c=>!featured.some(x=>x.id===c.id)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,6);res.json({companies:list,featured,recent})});
app.get('/api/companies/:id',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});res.json({company:publicCompany(c),isOwner:c.ownerUsername===req.username})});
app.post('/api/companies',(req,res)=>{ensureCompanyData();if(city.companies.filter(c=>c.ownerUsername===req.username).length>=3)return res.status(400).json({error:'Você já possui o limite de 3 empresas.'});const name=ct(req.body?.name,80),description=ct(req.body?.description,500),companyImage=validCompanyImage(req.body?.companyImage);if(companyImage===null)return res.status(400).json({error:'Foto da empresa inválida ou grande demais.'});if(!name)return res.status(400).json({error:'Informe o nome da empresa.'});if(city.companies.some(c=>c.name.toLowerCase()===name.toLowerCase()))return res.status(400).json({error:'Já existe uma empresa com esse nome.'});const p=productInput(req.body?.product||{});if(p.error)return res.status(400).json({error:p.error});const c={id:companyId(),name,description,companyImage:companyImage||'',ownerUsername:req.username,ownerName:req.user.name,balance:0,totalSales:0,salesCount:0,xp:0,level:1,sales:[],featured:false,createdAt:new Date().toISOString(),products:[p.product],nextFeeAt:new Date(Date.now()+7*24*60*60*1000).toISOString()};city.companies.push(c);req.user.companyIds=Array.isArray(req.user.companyIds)?req.user.companyIds:[];req.user.companyIds.push(c.id);saveData();res.json({message:'Empresa criada com sucesso!',company:publicCompany(c)})});
app.put('/api/companies/:id',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});if(c.ownerUsername!==req.username)return res.status(403).json({error:'Apenas o dono pode modificar a empresa.'});if(req.body?.companyImage!==undefined){const image=validCompanyImage(req.body.companyImage);if(image===null)return res.status(400).json({error:'Foto da empresa inválida ou grande demais.'});c.companyImage=image}if(req.body?.description!==undefined)c.description=ct(req.body.description,500);saveData();res.json({message:'Empresa atualizada!',company:publicCompany(c)})});
app.post('/api/companies/:id/products',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});if(c.ownerUsername!==req.username)return res.status(403).json({error:'Apenas o dono pode adicionar produtos.'});if(c.products.length>=50)return res.status(400).json({error:'Limite de 50 produtos.'});const p=productInput(req.body||{});if(p.error)return res.status(400).json({error:p.error});c.products.push(p.product);saveData();res.json({message:'Produto adicionado!',company:publicCompany(c)})});
app.put('/api/companies/:id/products/:productId',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});if(c.ownerUsername!==req.username)return res.status(403).json({error:'Apenas o dono pode modificar produtos.'});const p=c.products.find(x=>x.id===req.params.productId);if(!p)return res.status(404).json({error:'Produto não encontrado.'});if(p.type!=='veiculo')return res.status(400).json({error:'Apenas veículos possuem personalização visual.'});p.vehicleCustomization=vehicleCustomization(req.body?.vehicleCustomization);if(req.body?.emoji)p.emoji=ct(req.body.emoji,8);saveData();res.json({message:'Veículo personalizado com sucesso!',product:p})});app.delete('/api/companies/:id/products/:productId',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});if(c.ownerUsername!==req.username)return res.status(403).json({error:'Apenas o dono pode remover produtos.'});const i=c.products.findIndex(p=>p.id===req.params.productId);if(i<0)return res.status(404).json({error:'Produto não encontrado.'});c.products.splice(i,1);saveData();res.json({message:'Produto removido.'})});
app.post('/api/companies/:id/products/:productId/buy',(req,res)=>{ensureCompanyData();const c=city.companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Empresa não encontrada.'});const p=c.products.find(x=>x.id===req.params.productId);if(!p)return res.status(404).json({error:'Produto não encontrado.'});const qty=Math.max(1,Math.min(99,Math.floor(Number(req.body?.quantity)||1))),total=p.price*qty;if(req.user.money<total)return res.status(400).json({error:'Dinheiro insuficiente.'});req.user.money-=total;const seller=users[c.ownerUsername];if(seller)seller.money=(Number(seller.money)||0)+total;c.balance=(Number(c.balance)||0)+total;c.totalSales=(Number(c.totalSales)||0)+total;c.salesCount=(Number(c.salesCount)||0)+qty;c.xp=(Number(c.xp)||0)+Math.max(1,Math.floor(total/10));c.level=Math.max(1,1+Math.floor((Number(c.xp)||0)/500));c.sales=Array.isArray(c.sales)?c.sales:[];c.sales.unshift({date:new Date().toISOString(),buyer:req.user.name,product:p.name,quantity:qty,total});c.sales=c.sales.slice(0,100);req.user.companyInventory=req.user.companyInventory||{};req.user.companyInventory[p.id]=(Number(req.user.companyInventory[p.id])||0)+qty;saveData();res.json({message:p.name+' comprado! Foi para seu inventário.',user:req.user})});
app.get('/api/company-inventory',(req,res)=>{ensureCompanyData();const inv=req.user.companyInventory||{},items=[];city.companies.forEach(c=>c.products.forEach(p=>{const q=Number(inv[p.id]||0);if(q>0)items.push({companyId:c.id,companyName:c.name,product:p,quantity:q})}));res.json({items})});
app.post('/api/company-inventory/use',(req,res)=>{ensureCompanyData();const id=String(req.body?.productId||''),inv=req.user.companyInventory||{};if(Number(inv[id]||0)<1)return res.status(400).json({error:'Você não possui esse produto.'});let p=null;for(const c of city.companies){p=c.products.find(x=>x.id===id);if(p)break}if(!p)return res.status(404).json({error:'Produto não encontrado.'});const e=p.effects||{};if(p.type==='consumivel'){if(e.hunger)req.user.hunger=Math.max(0,Math.min(100,Number(req.user.hunger||0)+e.hunger));if(e.hydration)req.user.hydration=Math.max(0,Math.min(100,Number(req.user.hydration||0)+e.hydration));if(e.energy)req.user.energy=Math.max(0,Math.min(100,Number(req.user.energy||0)+e.energy));if(e.life)req.user.life=Math.max(0,Math.min(100,Number(req.user.life||0)+e.life));inv[id]--;saveData();return res.json({message:p.name+' usado e consumido.',user:req.user})}req.user.equippedCompanyProducts=req.user.equippedCompanyProducts||{};req.user.equippedCompanyProducts[id]=true;saveData();res.json({message:p.name+' foi ativado/equipado.',user:req.user})});
app.get('/api/shop',(req,res)=>res.json(shopItems));
app.post('/api/shop/buy',(req,res)=>{const item=shopItems.find(x=>x.id===Number(req.body.id??req.body.itemId));const qty=Math.max(1,Number(req.body.quantity)||1);if(!item)return res.status(404).json({error:'Item não encontrado'});const total=item.price*qty;if(req.user.money<total)return res.status(400).json({error:'Dinheiro insuficiente'});req.user.money-=total;req.user.inventory[item.id]=(req.user.inventory[item.id]||0)+qty;saveData();res.json({message:`${item.name} comprado!`,user:req.user})});
app.post('/api/shop/use',(req,res)=>{const item=shopItems.find(x=>x.id===Number(req.body.id??req.body.itemId));if(!item)return res.status(404).json({error:'Item não encontrado'});if((req.user.inventory[item.id]||0)<1)return res.status(400).json({error:'Você não possui este item'});req.user.inventory[item.id]--;if(item.hunger)req.user.hunger=Math.min(100,req.user.hunger+item.hunger);if(item.hydration)req.user.hydration=Math.min(100,req.user.hydration+item.hydration);if(item.energy)req.user.energy=Math.min(100,req.user.energy+item.energy);saveData();res.json({message:`${item.name} usado!`,user:req.user})});
app.get('/api/hospital',(req,res)=>res.json({services:hospitalServices}));
app.post('/api/hospital/treat',(req,res)=>{const s=hospitalServices.find(x=>x.id===Number(req.body.serviceId??req.body.id));if(!s)return res.status(404).json({error:'Serviço não encontrado'});if(req.user.money<s.price)return res.status(400).json({error:'Dinheiro insuficiente'});req.user.money-=s.price;req.user.life=Math.min(100,req.user.life+s.life);saveData();res.json({message:'Atendimento realizado!',user:req.user})});
app.get('/api/inventory',(req,res)=>res.json({inventory:req.user.inventory||{},items:shopItems}));
app.post('/api/inventory/use',(req,res)=>{const item=shopItems.find(x=>x.id===Number(req.body.itemId??req.body.id));if(!item)return res.status(404).json({error:'Item não encontrado'});if((req.user.inventory[item.id]||0)<1)return res.status(400).json({error:'Você não possui este item'});req.user.inventory[item.id]--;if(item.hunger)req.user.hunger=Math.min(100,req.user.hunger+item.hunger);if(item.hydration)req.user.hydration=Math.min(100,req.user.hydration+item.hydration);if(item.energy)req.user.energy=Math.min(100,req.user.energy+item.energy);saveData();res.json({message:`${item.name} usado!`,user:req.user})});
app.get('/api/bank',(req,res)=>res.json({bankBalance:Number(req.user.bankBalance||0),transfers:req.user.transactions||[]}));
app.post('/api/bank/deposit',(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Valor inválido'});if(req.user.money<amount)return res.status(400).json({error:'Dinheiro insuficiente'});req.user.money-=amount;req.user.bankBalance=Number(req.user.bankBalance||0)+amount;(req.user.transactions||(req.user.transactions=[])).push({date:new Date(),type:'Depósito',person:req.user.name,amount});saveData();res.json({message:'Depósito realizado!',money:req.user.money,bankBalance:req.user.bankBalance,user:req.user})});
app.post('/api/bank/withdraw',(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Valor inválido'});if(Number(req.user.bankBalance||0)<amount)return res.status(400).json({error:'Saldo bancário insuficiente'});req.user.bankBalance-=amount;req.user.money=(req.user.money||0)+amount;(req.user.transactions||(req.user.transactions=[])).push({date:new Date(),type:'Saque',person:req.user.name,amount});saveData();res.json({message:'Saque realizado!',money:req.user.money,bankBalance:req.user.bankBalance,user:req.user})});
app.post('/api/bank/transfer',(req,res)=>{const amount=Number(req.body.amount),dest=String(req.body.username||'').trim();if(!dest||!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Preencha os dados da transferência'});if(dest===req.username)return res.status(400).json({error:'Você não pode transferir para si mesmo'});if(Number(req.user.bankBalance||0)<amount)return res.status(400).json({error:'Saldo bancário insuficiente'});const target=users[dest];if(!target)return res.status(404).json({error:'Usuário destinatário não encontrado'});req.user.bankBalance-=amount;target.bankBalance=Number(target.bankBalance||0)+amount;(req.user.transactions||(req.user.transactions=[])).push({date:new Date(),type:'Transferência enviada',person:dest,amount});(target.transactions||(target.transactions=[])).push({date:new Date(),type:'Transferência recebida',person:req.username,amount});saveData();res.json({message:'Transferência realizada!',money:req.user.money,bankBalance:req.user.bankBalance,user:req.user})});
app.get('/api/mayor/users',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode gerenciar contas'});const list=Object.values(users).filter(u=>u.username!==req.user.username).map(u=>({name:u.name,username:u.username,jobName:u.jobName,level:u.level,xp:u.xp,money:u.money}));res.json({users:list})});
app.delete('/api/mayor/users/:username',async(req,res)=>{try{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode excluir contas'});const username=String(req.params.username||'').trim();if(!username)return res.status(400).json({error:'Usuário inválido'});if(username===req.user.username)return res.status(400).json({error:'O prefeito não pode excluir a própria conta'});const target=users[username];if(!target)return res.status(404).json({error:'Conta não encontrada'});delete users[username];city.population=Math.max(0,Number(city.population||0)-1);await db.set('users',users);await db.set('city',city);res.json({message:'Conta excluída permanentemente.',username})}catch(e){console.error('Falha ao excluir conta:',e);res.status(500).json({error:'Não foi possível excluir a conta permanentemente.'})}});
app.get('/api/players',(req,res)=>res.json(Object.values(users).map(u=>({name:u.name,username:u.username,jobName:u.jobName,level:u.level,xp:u.xp,money:u.money}))));
app.get('/api/players/:username',(req,res)=>{const u=users[req.params.username];if(!u)return res.status(404).json({error:'Jogador não encontrado'});res.json({name:u.name,username:u.username,jobName:u.jobName,level:u.level,xp:u.xp,money:u.money})});
const defaultAchievements=[{id:'first_mission',name:'Primeira missão',description:'Complete sua primeira missão.',icon:'🎯'},{id:'first_purchase',name:'Primeira compra',description:'Compre seu primeiro item.',icon:'🛒'},{id:'citizen',name:'Cidadão',description:'Faça parte de Sorokiba.',icon:'🏙️'}];
app.get('/api/achievements',(req,res)=>res.json(defaultAchievements.filter(a=>(req.user.achievements||[]).includes(a.id))));
app.get('/api/missions',(req,res)=>{const job=jobs.find(j=>j.id===req.user.jobId);const userMissions=req.user.missions||[];const active=userMissions.filter(m=>m.status==='active');const state=getMissionState(req.user);if(state.cooldownUntil){const cooldownMs=new Date(state.cooldownUntil).getTime();if(!Number.isFinite(cooldownMs)||cooldownMs<=Date.now()){req.user.missionCooldownUntil=null;req.user.missionBatchCount=0;saveData()}}const finalState=getMissionState(req.user);res.json({job:{name:job.name,task:job.task},active,history:userMissions.filter(m=>m.status==='completed').slice(-10),missionsRemaining:active.length?0:finalState.remaining,missionsUsed:finalState.batchCount,cooldownUntil:finalState.cooldownUntil})});
app.post('/api/missions/start',(req,res)=>{if(!req.user.missions)req.user.missions=[];const state=getMissionState(req.user);if(state.cooldownUntil){const msLeft=new Date(state.cooldownUntil).getTime()-Date.now();if(msLeft>0){const minLeft=Math.floor(msLeft/60000),secLeft=Math.floor(msLeft%60000/1000);return res.status(400).json({error:`Você já fez 2 missões. Aguarde ${minLeft}:${String(secLeft).padStart(2,'0')} para receber mais 2 missões.`,cooldownUntil:state.cooldownUntil})}req.user.missionCooldownUntil=null;req.user.missionBatchCount=0}if(Number(req.user.missionBatchCount)>=2){startCooldownIfNeeded(req.user);saveData();return res.status(400).json({error:'Você já fez 2 missões. Aguarde 30 minutos para receber mais 2 missões.',cooldownUntil:req.user.missionCooldownUntil})}const activeMissions=req.user.missions.filter(m=>m.status==='active');if(activeMissions.length>0)return res.status(400).json({error:'Você já tem uma missão ativa'});const mission=createMission(req.user.jobId,req.username);if(!mission)return res.status(400).json({error:'Sem perguntas disponíveis para sua profissão. Volte mais tarde.'});req.user.missions.push(mission);saveData();res.json({message:`Missão iniciada! (${Number(req.user.missionBatchCount)+1}/2)`,mission:{id:mission.id,jobId:mission.jobId,started_at:mission.started_at,duration_seconds:mission.duration_seconds,questions:mission.questions,rewardXp:mission.rewardXp,rewardMoney:mission.rewardMoney}})});
const registerMissionUse=user=>{user.missionBatchCount=Number(user.missionBatchCount||0)+1;if(user.missionBatchCount>=2)startCooldownIfNeeded(user)};
app.post('/api/missions/:id/answer',(req,res)=>{const m=(req.user.missions||[]).find(x=>x.id===req.params.id&&x.status==='active');if(!m)return res.status(404).json({error:'Missão não encontrada'});const qIndex=Number(req.body.questionIndex),answer=Number(req.body.answer),qid=m.questionRefs[qIndex],q=findQuestionById(qid);if(!q)return res.status(400).json({error:'Pergunta não encontrada'});m.answers=m.answers||[];if(m.answers[qIndex]!==undefined)return res.status(400).json({error:'Essa pergunta já foi respondida'});m.answers[qIndex]=answer;req.user.answeredQuestions=req.user.answeredQuestions||[];if(!req.user.answeredQuestions.includes(q.id))req.user.answeredQuestions.push(q.id);if(answer===q.correct)req.user.xp=(req.user.xp||0)+Math.max(1,Math.floor((m.rewardXp||20)/m.questions.length));m.correctCount=(m.correctCount||0)+(answer===q.correct?1:0);const final=m.answers.filter(v=>v!==undefined).length>=m.questions.length;if(final){m.status='completed';m.createdAt=new Date();registerMissionUse(req.user);req.user.money=(req.user.money||0)+(m.rewardMoney||0);saveData()}res.json({correct:answer===q.correct,correctIndex:q.correct,correctOptionText:q.options[q.correct],final,message:final?'Missão concluída!':(answer===q.correct?'Resposta correta!':'Resposta incorreta!'),xpGiven:final?m.rewardXp||0:0,moneyGiven:final?m.rewardMoney||0:0,user:{...req.user}})});
app.post('/api/missions/:id/complete',(req,res)=>{const m=(req.user.missions||[]).find(x=>x.id===req.params.id&&x.status==='active');if(!m)return res.status(404).json({error:'Missão não encontrada'});m.status='completed';m.createdAt=new Date();registerMissionUse(req.user);saveData();res.json({message:'Missão encerrada.',user:{...req.user}})});
app.get('/api/news',(req,res)=>res.json(city.news));app.get('/api/events',(req,res)=>res.json(city.events));
app.get('/api/proposals',(req,res)=>{if(req.user.isMayor)return res.json(city.proposals.filter(p=>p.status==='pending'));return res.json(city.proposals.filter(p=>p.authorUsername===req.username||(!p.authorUsername&&p.author===req.user.name)))});
app.post('/api/proposals',(req,res)=>{const{title,description}=req.body;if(!title||!description)return res.status(400).json({error:'Preencha todos os campos'});city.proposals.push({id:`prop_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,author:req.user.name,authorUsername:req.username,title,description,status:'pending',createdAt:new Date()});saveData();res.json({message:'Proposta enviada com sucesso!'})});
app.post('/api/mayor/proposals/:id/decide',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode decidir'});const{status,response}=req.body;if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Resultado inválido'});const proposal=city.proposals.find(p=>p.id===req.params.id);if(!proposal)return res.status(404).json({error:'Proposta não encontrada'});if(proposal.status!=='pending')return res.status(400).json({error:'Esta proposta já foi avaliada'});proposal.status=status;proposal.response=String(response||'').trim();proposal.decidedAt=new Date();saveData();res.json({message:status==='approved'?'Proposta aprovada e resultado enviado ao cidadão!':'Proposta rejeitada e resultado enviado ao cidadão!'})});

app.get('/api/mayor',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});res.json({population:city.population,treasury:city.treasury,economy:city.economy,infrastructure:city.infrastructure,quality:city.quality,taxRate:city.taxRate,news:city.news,events:city.events,proposals:city.proposals.filter(p=>p.status==='pending')})});

app.post('/api/mayor/news',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});const{title,text}=req.body;if(!title||!text)return res.status(400).json({error:'Preencha título e texto'});city.news.unshift({id:`news_${Date.now()}`,title,text,date:new Date()});saveData();res.json({message:'Notícia publicada!'})});
app.post('/api/mayor/events',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});const{title,description}=req.body;if(!title||!description)return res.status(400).json({error:'Preencha título e descrição'});city.events.unshift({id:`event_${Date.now()}`,title,description,date:new Date()});saveData();res.json({message:'Evento criado!'})});

const allQuestions=()=>Object.entries(questionBank).flatMap(([jobId,arr])=>arr.map(q=>({...q,jobId})));
app.get('/api/mayor/questions',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});res.json(allQuestions())});
app.post('/api/mayor/questions',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});const{jobId,text,options,correct,difficulty}=req.body;if(!jobId||!text||!Array.isArray(options)||options.length<2)return res.status(400).json({error:'Preencha todos os campos'});if(!questionBank[jobId])questionBank[jobId]=[];const q={id:`q_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,text,options,correct:Number(correct)||0,difficulty:Number(difficulty)||1};questionBank[jobId].push(q);saveData();res.json({message:'Pergunta adicionada!',question:{...q,jobId}})});
app.put('/api/mayor/questions/:id',(req,res)=>{if(!req.user.isMayor)return res.status(403).json({error:'Apenas o prefeito pode acessar'});const q=findQuestionById(req.params.id);if(!q)return res.status(404).json({error:'Pergunta não encontrada'});if(req.body.text)q.text=req.body.text;if(Array.isArray(req.body.options)&&req.body.options.length>=2)q.options=req.body.options;if(req.body.correct!==undefined)q.correct=Number(req.body.correct);if(req.body.difficulty!==undefined)q.difficulty=Number(req.body.difficulty);saveData();res.json({message:'Pergunta atualizada!'})});

app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));

db.init().then(()=>loadData()).then(()=>{app.listen(process.env.PORT||3000,()=>console.log(`🏙️ Sorokiba rodando na porta ${process.env.PORT||3000}`))}).catch(err=>{console.error('❌ Falha ao inicializar o banco:',err);process.exit(1)});
