"use strict";
const express = require("express");
const path = require("path");
const crypto = require("crypto");
const { Pool } = require("pg");

const app = express();
const PORT = Number(process.env.PORT) || 10000;
if (!process.env.DATABASE_URL) { console.error("DATABASE_URL não configurada."); process.exit(1); }
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized:false }, max:10, idleTimeoutMillis:30000, connectionTimeoutMillis:10000 });
app.use(express.json({limit:"3mb"}));
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname,"public")));

const now = () => new Date();
const dayKey = () => new Date().toISOString().slice(0,10);
function hashPassword(password){const salt=crypto.randomBytes(16).toString("hex");const hash=crypto.createHash("sha256").update(salt+password).digest("hex");return `${salt}:${hash}`;}
function verifyPassword(password,stored){if(!stored||!stored.includes(":"))return false;const [salt,original]=stored.split(":");const hash=crypto.createHash("sha256").update(salt+password).digest("hex");return crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(original));}
function token(){return crypto.randomBytes(32).toString("hex");}
function cleanUser(u){return {id:u.id,username:u.username,name:u.name,role:u.role,xp:Number(u.xp||0),level:Number(u.level||1),money:Number(u.money||0),bank:Number(u.bank||0),job:u.job||null,health:Number(u.health??100),hunger:Number(u.hunger??100),reputation:Number(u.reputation??50),inventory:u.inventory||[],achievements:u.achievements||{},created_at:u.created_at};}
function xpLevel(xp){let level=1,rest=Math.max(0,Number(xp)||0);while(rest>=level*100){rest-=level*100;level++;}return {level,rest};}
async function addXP(client,userId,amount){const r=await client.query("SELECT xp FROM users WHERE id=$1 FOR UPDATE",[userId]);if(!r.rows.length)return;const total=Number(r.rows[0].xp||0)+Math.max(0,Number(amount)||0);const {level}=xpLevel(total);await client.query("UPDATE users SET xp=$1, level=$2 WHERE id=$3",[total,level,userId]);}
async function logActivity(client,userId,type,title,details={}){await client.query("INSERT INTO activities(user_id,type,title,details) VALUES($1,$2,$3,$4)",[userId,type,title,JSON.stringify(details)]);}
async function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({ok:false,error:"Não autenticado."});const r=await pool.query(`SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=$1 AND s.expires_at>NOW() LIMIT 1`,[h.slice(7).trim()]);if(!r.rows.length)return res.status(401).json({ok:false,error:"Sessão expirada."});req.user=r.rows[0];next();}catch(e){console.error(e);res.status(500).json({ok:false,error:"Erro de autenticação."});}}
function mayor(req,res,next){if(req.user.role!=="mayor")return res.status(403).json({ok:false,error:"Somente o prefeito pode realizar esta ação."});next();}

async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'citizen',xp INTEGER NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 1,money BIGINT NOT NULL DEFAULT 500,bank BIGINT NOT NULL DEFAULT 50,job TEXT,health INTEGER NOT NULL DEFAULT 100,hunger INTEGER NOT NULL DEFAULT 100,reputation INTEGER NOT NULL DEFAULT 50,inventory JSONB NOT NULL DEFAULT '[]',achievements JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 const alters=["ADD COLUMN IF NOT EXISTS health INTEGER NOT NULL DEFAULT 100","ADD COLUMN IF NOT EXISTS hunger INTEGER NOT NULL DEFAULT 100","ADD COLUMN IF NOT EXISTS reputation INTEGER NOT NULL DEFAULT 50","ADD COLUMN IF NOT EXISTS inventory JSONB NOT NULL DEFAULT '[]'::jsonb","ADD COLUMN IF NOT EXISTS achievements JSONB NOT NULL DEFAULT '{}'::jsonb"];for(const a of alters)await pool.query(`ALTER TABLE users ${a}`);
 await pool.query(`CREATE TABLE IF NOT EXISTS sessions(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS city(id INTEGER PRIMARY KEY,name TEXT NOT NULL DEFAULT 'Sorokiba',gdp BIGINT NOT NULL DEFAULT 100000,population INTEGER NOT NULL DEFAULT 0,territory INTEGER NOT NULL DEFAULT 10,treasury BIGINT NOT NULL DEFAULT 1000,infrastructure INTEGER NOT NULL DEFAULT 50,quality INTEGER NOT NULL DEFAULT 70,tax INTEGER NOT NULL DEFAULT 5)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS jobs(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,description TEXT DEFAULT '',required_level INTEGER NOT NULL DEFAULT 1,reward INTEGER NOT NULL DEFAULT 50,xp_reward INTEGER NOT NULL DEFAULT 20,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS job_tasks(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,job_name TEXT NOT NULL,day DATE NOT NULL,reward INTEGER NOT NULL,xp_reward INTEGER NOT NULL,completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,day))`);
 await pool.query(`CREATE TABLE IF NOT EXISTS missions(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,day DATE NOT NULL,title TEXT NOT NULL,reward INTEGER NOT NULL,xp_reward INTEGER NOT NULL,completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,day))`);
 await pool.query(`CREATE TABLE IF NOT EXISTS foods(id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,hunger INTEGER NOT NULL,description TEXT NOT NULL)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS purchases(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,food_id TEXT NOT NULL,price INTEGER NOT NULL,hunger INTEGER NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS news(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,content TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Comunicado',image TEXT DEFAULT '',author_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS events(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,author_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS proposals(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,title TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',response TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS bank_transactions(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,amount BIGINT NOT NULL,description TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS activities(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,title TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`INSERT INTO city(id,name,gdp,population,territory,treasury,infrastructure,quality,tax) VALUES(1,'Sorokiba',100000,0,10,1000,50,70,5) ON CONFLICT(id) DO NOTHING`);
 const foods=[['agua','Água',5,5,'Uma garrafa de água.'],['lanche','Lanche',15,15,'Um lanche simples.'],['pizza','Pizza',35,30,'Uma pizza deliciosa.'],['hamburguer','Hambúrguer',50,45,'Um hambúrguer completo.'],['comida','Refeição completa',75,65,'Uma refeição completa.'],['banquete','Banquete',120,100,'Uma grande refeição.']];for(const f of foods)await pool.query(`INSERT INTO foods(id,name,price,hunger,description) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,hunger=EXCLUDED.hunger,description=EXCLUDED.description`,f);
 const jobs=[['Entregador','Faça entregas pela cidade.',1,50,20],['Comerciante','Trabalhe nas lojas da cidade.',2,80,30],['Guarda','Ajude a proteger Sorokiba.',3,100,40],['Engenheiro','Trabalhe no desenvolvimento da cidade.',5,150,60],['Administrador','Ajude na administração de Sorokiba.',8,250,100]];for(const j of jobs)await pool.query(`INSERT INTO jobs(name,description,required_level,reward,xp_reward) VALUES($1,$2,$3,$4,$5) ON CONFLICT(name) DO NOTHING`,j);
 await pool.query(`UPDATE users SET health=100 WHERE health IS NULL`);await pool.query(`UPDATE users SET hunger=100 WHERE hunger IS NULL`);await pool.query(`UPDATE users SET reputation=50 WHERE reputation IS NULL`);await pool.query(`UPDATE city SET population=(SELECT COUNT(*) FROM users) WHERE id=1`);
 const c=await pool.query("SELECT COUNT(*)::int n FROM users");if(c.rows[0].n>0){await pool.query("UPDATE users SET role='mayor' WHERE id=(SELECT id FROM users ORDER BY id LIMIT 1) AND NOT EXISTS(SELECT 1 FROM users WHERE role='mayor')");}
}

app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,server:'Sorokiba',database:true});}catch(e){res.status(500).json({ok:false,database:false});}});
app.post('/api/register',async(req,res)=>{const client=await pool.connect();try{let {name,username,password}=req.body;if(!name||!username||!password)return res.status(400).json({ok:false,error:'Preencha todos os campos.'});name=String(name).trim();username=String(username).trim().toLowerCase();password=String(password);if(username.length<3||username.length>20)return res.status(400).json({ok:false,error:'O usuário deve ter entre 3 e 20 caracteres.'});if(password.length<6)return res.status(400).json({ok:false,error:'A senha precisa ter pelo menos 6 caracteres.'});await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM users WHERE LOWER(username)=$1',[username]);if(exists.rows.length){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'Esse usuário já existe.'});}const n=await client.query('SELECT COUNT(*)::int n FROM users');const role=n.rows[0].n===0?'mayor':'citizen';const u=await client.query(`INSERT INTO users(username,name,password,role,job) VALUES($1,$2,$3,$4,$5) RETURNING *`,[username,name,hashPassword(password),role,'Entregador']);await client.query('UPDATE city SET population=(SELECT COUNT(*) FROM users) WHERE id=1');const t=token();await client.query(`INSERT INTO sessions(user_id,token,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')`,[u.rows[0].id,t]);await logActivity(client,u.rows[0].id,'account','Conta criada',{role});await client.query('COMMIT');res.status(201).json({ok:true,token:t,user:cleanUser(u.rows[0])});}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({ok:false,error:'Erro ao criar conta.'});}finally{client.release();}});
app.post('/api/login',async(req,res)=>{try{const username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||'');const r=await pool.query('SELECT * FROM users WHERE LOWER(username)=$1',[username]);if(!r.rows.length||!verifyPassword(password,r.rows[0].password))return res.status(401).json({ok:false,error:'Usuário ou senha incorretos.'});const t=token();await pool.query(`INSERT INTO sessions(user_id,token,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')`,[r.rows[0].id,t]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'login','Login realizado','{}')`,[r.rows[0].id]);res.json({ok:true,token:t,user:cleanUser(r.rows[0])});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Erro ao entrar na conta.'});}});
app.post('/api/logout',auth,async(req,res)=>{try{const t=req.headers.authorization.slice(7).trim();await pool.query('DELETE FROM sessions WHERE token=$1',[t]);res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:'Erro ao sair.'});}});

app.get('/api/state',auth,async(req,res)=>{try{const [u,c,n,e,p]=await Promise.all([pool.query('SELECT * FROM users WHERE id=$1',[req.user.id]),pool.query('SELECT * FROM city WHERE id=1'),pool.query(`SELECT n.id,n.title,n.content AS text,n.category,n.image,n.created_at AS date,u.name AS author FROM news n LEFT JOIN users u ON u.id=n.author_id ORDER BY n.created_at DESC LIMIT 50`),pool.query(`SELECT e.id,e.title,e.description AS text,e.created_at AS date,u.name AS author FROM events e LEFT JOIN users u ON u.id=e.author_id ORDER BY e.created_at DESC LIMIT 50`),pool.query(`SELECT p.id,p.title,p.description AS text,p.status,p.response,p.created_at AS date,u.name AS author FROM proposals p LEFT JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC LIMIT 50`)]);const city=c.rows[0];res.json({ok:true,user:cleanUser(u.rows[0]),city,news:n.rows,events:e.rows,proposals:p.rows});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Não foi possível carregar o estado do jogo.'});}});
app.get('/api/jobs',auth,async(req,res)=>{const r=await pool.query('SELECT id,name,description,required_level AS xp,reward, xp_reward AS "taskXP" FROM jobs WHERE active=true ORDER BY required_level');const out={};for(const j of r.rows)out[j.name]={id:j.id,xp:Number(j.xp),reward:Number(j.reward),taskXP:Number(j.taskXP),taskMoney:Number(j.reward),description:j.description};res.json(out);});
app.post('/api/job',auth,async(req,res)=>{try{const r=await pool.query('SELECT * FROM jobs WHERE name=$1 AND active=true',[req.body.job]);if(!r.rows.length)return res.status(404).json({ok:false,error:'Emprego não encontrado.'});const j=r.rows[0];if(req.user.level<j.required_level)return res.status(403).json({ok:false,error:`Você precisa estar no nível ${j.required_level}.`});await pool.query('UPDATE users SET job=$1 WHERE id=$2',[j.name,req.user.id]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'job','Emprego escolhido',$2)`,[req.user.id,JSON.stringify({job:j.name})]);res.json({ok:true});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Erro ao escolher emprego.'});}});
app.get('/api/job-task',auth,async(req,res)=>{const j=await pool.query('SELECT * FROM jobs WHERE name=$1 AND active=true',[req.user.job]);if(!j.rows.length)return res.status(400).json({ok:false,error:'Você não possui um emprego válido.'});const done=await pool.query('SELECT 1 FROM job_tasks WHERE user_id=$1 AND day=$2',[req.user.id,dayKey()]);const x=j.rows[0];res.json({ok:true,title:`Tarefa de ${x.name}`,job:x.name,xp:Number(x.xp_reward),money:Number(x.reward),done:!!done.rows.length});});
app.post('/api/job-task',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const u=(await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];const j=(await client.query('SELECT * FROM jobs WHERE name=$1 AND active=true',[u.job])).rows[0];if(!j){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Você não possui um emprego válido.'});}const d=await client.query('SELECT 1 FROM job_tasks WHERE user_id=$1 AND day=$2',[u.id,dayKey()]);if(d.rows.length){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'Você já concluiu a tarefa de hoje.'});}await client.query('UPDATE users SET money=money+$1 WHERE id=$2',[j.reward,u.id]);await addXP(client,u.id,j.xp_reward);await client.query('INSERT INTO job_tasks(user_id,job_name,day,reward,xp_reward) VALUES($1,$2,$3,$4,$5)',[u.id,j.name,dayKey(),j.reward,j.xp_reward]);await logActivity(client,u.id,'job_task','Tarefa do emprego concluída',{job:j.name,reward:j.reward,xp:j.xp_reward});await client.query('COMMIT');res.json({ok:true});}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({ok:false,error:'Erro ao concluir tarefa.'});}finally{client.release();}});
app.get('/api/mission',auth,async(req,res)=>{const done=await pool.query('SELECT 1 FROM missions WHERE user_id=$1 AND day=$2',[req.user.id,dayKey()]);res.json({ok:true,title:'Ajude Sorokiba hoje',xp:30,money:75,done:!!done.rows.length});});
app.post('/api/mission',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const d=await client.query('SELECT 1 FROM missions WHERE user_id=$1 AND day=$2',[req.user.id,dayKey()]);if(d.rows.length){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'Você já concluiu a missão de hoje.'});}await client.query('UPDATE users SET money=money+75,reputation=LEAST(100,reputation+2) WHERE id=$1',[req.user.id]);await addXP(client,req.user.id,30);await client.query(`INSERT INTO missions(user_id,day,title,reward,xp_reward) VALUES($1,$2,$3,$4,$5)`,[req.user.id,dayKey(),'Ajude Sorokiba hoje',75,30]);await logActivity(client,req.user.id,'mission','Missão diária concluída',{reward:75,xp:30});await client.query('COMMIT');res.json({ok:true});}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({ok:false,error:'Erro ao concluir missão.'});}finally{client.release();}});
app.get('/api/market',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM foods ORDER BY price');const out={};for(const f of r.rows)out[f.name]={id:f.id,price:Number(f.price),hunger:Number(f.hunger),description:f.description};res.json(out);});
app.post('/api/buy-food',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const f=(await client.query('SELECT * FROM foods WHERE id=$1 OR name=$1',[req.body.food])).rows[0];if(!f){await client.query('ROLLBACK');return res.status(404).json({ok:false,error:'Alimento não encontrado.'});}const u=(await client.query('SELECT money FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(Number(u.money)<Number(f.price)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Dinheiro insuficiente.'});}await client.query('UPDATE users SET money=money-$1,hunger=LEAST(100,hunger+$2) WHERE id=$3',[f.price,f.hunger,req.user.id]);await client.query('INSERT INTO purchases(user_id,food_id,price,hunger) VALUES($1,$2,$3,$4)',[req.user.id,f.id,f.price,f.hunger]);await logActivity(client,req.user.id,'purchase','Alimento comprado',{food:f.name,price:f.price,hunger:f.hunger});await client.query('UPDATE city SET treasury=treasury+$1,gdp=gdp+$1 WHERE id=1',[f.price]);await client.query('COMMIT');res.json({ok:true});}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({ok:false,error:'Erro ao comprar alimento.'});}finally{client.release();}});
app.post('/api/health',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const u=(await client.query('SELECT money FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(Number(u.money)<50){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Você precisa de $50.'});}await client.query('UPDATE users SET money=money-50,health=LEAST(100,health+30) WHERE id=$1',[req.user.id]);await logActivity(client,req.user.id,'health','Consulta de saúde',{cost:50});await client.query('UPDATE city SET treasury=treasury+50,gdp=gdp+50 WHERE id=1');await client.query('COMMIT');res.json({ok:true});}catch(e){try{await client.query('ROLLBACK')}catch{}res.status(500).json({ok:false,error:'Erro ao cuidar da saúde.'});}finally{client.release();}});

app.get('/api/news',async(req,res)=>{const r=await pool.query(`SELECT n.id,n.title,n.content AS text,n.category,n.image,n.created_at AS date,u.name AS author FROM news n LEFT JOIN users u ON u.id=n.author_id ORDER BY n.created_at DESC LIMIT 100`);res.json({ok:true,news:r.rows});});
app.post('/api/news',auth,mayor,async(req,res)=>{try{const {title,text,content,category='Comunicado',image=''}=req.body;const body=text??content;if(!title||!body)return res.status(400).json({ok:false,error:'Título e texto são obrigatórios.'});const r=await pool.query('INSERT INTO news(title,content,category,image,author_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[String(title).trim(),String(body).trim(),String(category),String(image||''),req.user.id]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'news','Notícia publicada',$2)`,[req.user.id,JSON.stringify({newsId:r.rows[0].id,title})]);res.status(201).json({ok:true});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Erro ao publicar notícia.'});}});
app.post('/api/event',auth,mayor,async(req,res)=>{try{const {title,text,description}=req.body;const body=text??description;if(!title||!body)return res.status(400).json({ok:false,error:'Título e descrição são obrigatórios.'});await pool.query('INSERT INTO events(title,description,author_id) VALUES($1,$2,$3)',[String(title).trim(),String(body).trim(),req.user.id]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'event','Evento criado',$2)`,[req.user.id,JSON.stringify({title})]);res.status(201).json({ok:true});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Erro ao criar evento.'});}});
app.get('/api/proposals',auth,async(req,res)=>{const r=await pool.query(`SELECT p.id,p.title,p.description AS text,p.status,p.response,p.created_at AS date,u.name AS author FROM proposals p LEFT JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC`);res.json({ok:true,proposals:r.rows});});
app.post('/api/proposals',auth,async(req,res)=>{try{const text=String(req.body.text||req.body.description||'').trim();const title=String(req.body.title||'Proposta da cidade').trim();if(!text)return res.status(400).json({ok:false,error:'Escreva sua proposta.'});const r=await pool.query('INSERT INTO proposals(user_id,title,description) VALUES($1,$2,$3) RETURNING id',[req.user.id,title,text]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'proposal','Proposta enviada',$2)`,[req.user.id,JSON.stringify({proposalId:r.rows[0].id})]);res.status(201).json({ok:true});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Erro ao enviar proposta.'});}});
app.post('/api/proposals/:id',auth,mayor,async(req,res)=>{const approve=req.body.approve===true||req.body.status==='approved';const status=approve?'approved':'rejected';const response=String(req.body.response||'');const r=await pool.query('UPDATE proposals SET status=$1,response=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[status,response,req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:'Proposta não encontrada.'});await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'proposal','Proposta avaliada',$2)`,[req.user.id,JSON.stringify({proposalId:req.params.id,status})]);res.json({ok:true});});
app.patch('/api/proposals/:id',auth,mayor,async(req,res)=>{const status=req.body.status; if(!['approved','rejected','pending'].includes(status))return res.status(400).json({ok:false,error:'Status inválido.'});const r=await pool.query('UPDATE proposals SET status=$1,response=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[status,String(req.body.response||''),req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:'Proposta não encontrada.'});res.json({ok:true});});
app.post('/api/tax',auth,mayor,async(req,res)=>{const tax=Math.round(Number(req.body.tax));if(!Number.isFinite(tax)||tax<0||tax>30)return res.status(400).json({ok:false,error:'A taxa deve estar entre 0% e 30%.'});await pool.query('UPDATE city SET tax=$1 WHERE id=1',[tax]);await pool.query(`INSERT INTO activities(user_id,type,title,details) VALUES($1,'tax','Imposto alterado',$2)`,[req.user.id,JSON.stringify({tax})]);res.json({ok:true});});
app.get('/api/bank',auth,async(req,res)=>{const [u,t]=await Promise.all([pool.query('SELECT money,bank FROM users WHERE id=$1',[req.user.id]),pool.query('SELECT * FROM bank_transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id])]);res.json({ok:true,...u.rows[0],transactions:t.rows});});
async function bankMove(req,res,deposit){const client=await pool.connect();try{const amount=Math.floor(Number(req.body.amount));if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({ok:false,error:'Valor inválido.'});await client.query('BEGIN');const u=(await client.query('SELECT money,bank FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(deposit&&Number(u.money)<amount){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Dinheiro insuficiente.'});}if(!deposit&&Number(u.bank)<amount){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Saldo bancário insuficiente.'});}await client.query(`UPDATE users SET money=money${deposit?'-':'+'}$1,bank=bank${deposit?'+':'-'}$1 WHERE id=$2`,[amount,req.user.id]);await client.query(`INSERT INTO bank_transactions(user_id,type,amount,description) VALUES($1,$2,$3,$4)`,[req.user.id,deposit?'deposit':'withdraw',amount,deposit?'Depósito':'Saque']);await logActivity(client,req.user.id,'bank',deposit?'Depósito realizado':'Saque realizado',{amount});await client.query('COMMIT');res.json({ok:true});}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({ok:false,error:'Erro bancário.'});}finally{client.release();}}
app.post('/api/bank/deposit',auth,(req,res)=>bankMove(req,res,true));app.post('/api/bank/withdraw',auth,(req,res)=>bankMove(req,res,false));
app.get('/api/history',auth,async(req,res)=>{const r=await pool.query('SELECT id,type,title,details,created_at FROM activities WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200',[req.user.id]);res.json({ok:true,history:r.rows});});
app.get('/api/city',async(req,res)=>{const c=await pool.query('SELECT * FROM city WHERE id=1');const m=await pool.query("SELECT id,name,username,level FROM users WHERE role='mayor' LIMIT 1");res.json({ok:true,city:c.rows[0],mayor:m.rows[0]||null});});
app.post('/api/jobs',auth,mayor,async(req,res)=>{try{const {name,description='',requiredLevel=1,reward=50,xpReward=20}=req.body;if(!name)return res.status(400).json({ok:false,error:'Nome do emprego é obrigatório.'});const r=await pool.query('INSERT INTO jobs(name,description,required_level,reward,xp_reward,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[String(name).trim(),String(description),Math.max(1,Number(requiredLevel)||1),Math.max(0,Number(reward)||0),Math.max(0,Number(xpReward)||0),req.user.id]);res.status(201).json({ok:true,job:r.rows[0]});}catch(e){if(e.code==='23505')return res.status(409).json({ok:false,error:'Esse emprego já existe.'});res.status(500).json({ok:false,error:'Erro ao criar emprego.'});}});
app.get('/api/mayor/dashboard',auth,mayor,async(req,res)=>{const [c,u,j,p]=await Promise.all([pool.query('SELECT * FROM city WHERE id=1'),pool.query('SELECT COUNT(*)::int population,COALESCE(SUM(money),0)::bigint money,COALESCE(SUM(bank),0)::bigint bank FROM users'),pool.query('SELECT COUNT(*)::int total FROM jobs WHERE active=true'),pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='pending')::int pending FROM proposals")]);res.json({ok:true,city:c.rows[0],statistics:u.rows[0],jobs:j.rows[0],proposals:p.rows[0]});});
app.use('/api',(req,res)=>res.status(404).json({ok:false,error:'API não encontrada.'}));
app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);if(!res.headersSent)res.status(500).json({ok:false,error:'Erro interno do servidor.'});});

(async()=>{try{await pool.query('SELECT 1');await init();app.listen(PORT,'0.0.0.0',()=>console.log(`Sorokiba online na porta ${PORT}`));}catch(e){console.error('ERRO AO INICIAR:',e);process.exit(1);}})();
