const express=require("express"),cookie=require("cookie-parser"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const app=express(),PORT=process.env.PORT||3000,DB=path.join(__dirname,"data.json");
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],news:[],proposals:[],events:[],transactions:[],city:{population:0,gdp:100000,territory:10,treasury:1000,infrastructure:50,quality:70,tax:5}},null,2));
const read=()=>JSON.parse(fs.readFileSync(DB));const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));const sessions=new Map();
app.use(express.json());app.use(cookie());app.use(express.static(path.join(__dirname,"public")));
function makeHash(p){const salt=crypto.randomBytes(16).toString("hex");return{salt,hash:crypto.scryptSync(p,salt,64).toString("hex")}}
function valid(p,u){return crypto.timingSafeEqual(crypto.scryptSync(p,u.salt,64),Buffer.from(u.hash,"hex"))}
function safe(u){let{salt,hash,...x}=u;return x}
function auth(req,res,next){let d=read(),u=d.users.find(x=>x.username===sessions.get(req.cookies.sid));if(!u)return res.status(401).json({error:"Faça login."});req.user=u;next()}
function mayor(req,res,next){if(req.user.role!=="mayor")return res.status(403).json({error:"Área exclusiva do prefeito."});next()}
function login(u,res){let sid=crypto.randomBytes(32).toString("hex");sessions.set(sid,u.username);res.cookie("sid",sid,{httpOnly:true,sameSite:"lax",maxAge:604800000});res.json({user:safe(u)})}
app.post("/api/register",(req,res)=>{let d=read(),name=(req.body.name||"").trim(),username=(req.body.username||"").trim().toLowerCase(),password=req.body.password||"";if(name.length<2||username.length<3||password.length<6)return res.status(400).json({error:"Preencha nome, usuário e senha com 6+ caracteres."});if(d.users.some(u=>u.username===username))return res.status(409).json({error:"Usuário já existe."});let h=makeHash(password),u={id:Date.now(),name,username,...h,role:d.users.length===0?"mayor":"citizen",xp:0,level:1,money:500,reputation:50,job:"Entregador",lastMission:""};d.users.push(u);d.city.population++;write(d);login(u,res)});
app.post("/api/login",(req,res)=>{let d=read(),u=d.users.find(x=>x.username===(req.body.username||"").trim().toLowerCase());if(!u||!valid(req.body.password||"",u))return res.status(401).json({error:"Usuário ou senha incorretos."});login(u,res)});
app.post("/api/logout",auth,(req,res)=>{sessions.delete(req.cookies.sid);res.clearCookie("sid");res.json({ok:true})});
app.get("/api/state",auth,(req,res)=>{let d=read(),u=d.users.find(x=>x.id===req.user.id);res.json({user:safe(u),city:d.city,news:d.news,proposals:d.proposals,events:d.events})});
const jobs={Entregador:[0,40,"Entregar 3 encomendas"],Jornalista:[100,55,"Publicar a reportagem do dia"],Comerciante:[250,65,"Realizar 5 vendas"],Investigador:[500,80,"Resolver o caso diário"],Engenheiro:[1000,100,"Planejar uma melhoria urbana"],Empresário:[2000,130,"Criar um plano econômico"]};
app.get("/api/jobs",auth,(req,res)=>res.json(jobs));
app.post("/api/job",auth,(req,res)=>{let d=read(),u=d.users.find(x=>x.id===req.user.id),j=req.body.job;if(!jobs[j]||u.xp<jobs[j][0])return res.status(400).json({error:"Você ainda não desbloqueou esse emprego."});u.job=j;write(d);res.json({ok:true})});
app.get("/api/mission",auth,(req,res)=>{let d=read(),u=d.users.find(x=>x.id===req.user.id),j=jobs[u.job],day=new Date().toISOString().slice(0,10);res.json({title:j[2],xp:50+u.level*5,money:j[1],done:u.lastMission===day})});
app.post("/api/mission",auth,(req,res)=>{let d=read(),u=d.users.find(x=>x.id===req.user.id),j=jobs[u.job],day=new Date().toISOString().slice(0,10);if(u.lastMission===day)return res.status(400).json({error:"Missão de hoje já concluída."});let xp=50+u.level*5;u.lastMission=day;u.xp+=xp;u.money+=j[1];u.level=1+Math.floor(u.xp/500);u.reputation=Math.min(100,u.reputation+1);d.city.gdp+=j[1]*10;d.city.treasury+=Math.round(j[1]*.1);d.transactions.push({date:day,user:u.username,type:"Missão",value:j[1]});write(d);res.json({ok:true})});
app.post("/api/proposals",auth,(req,res)=>{let d=read(),text=(req.body.text||"").trim();if(!text)return res.status(400).json({error:"Escreva uma proposta."});d.proposals.unshift({id:Date.now(),author:req.user.username,text,status:"Pendente",date:new Date().toLocaleDateString("pt-BR")});write(d);res.json({ok:true})});
app.post("/api/proposals/:id",auth,mayor,(req,res)=>{let d=read(),p=d.proposals.find(x=>x.id==req.params.id);if(!p)return res.status(404).json({error:"Não encontrada."});p.status=req.body.approve?"Aprovada":"Recusada";write(d);res.json({ok:true})});
app.post("/api/news",auth,mayor,(req,res)=>{let d=read(),title=(req.body.title||"").trim(),text=(req.body.text||"").trim();if(!title||!text)return res.status(400).json({error:"Título e texto são obrigatórios."});d.news.unshift({id:Date.now(),title,text,category:req.body.category||"Comunicado",image:req.body.image||"",author:req.user.name,date:new Date().toLocaleDateString("pt-BR")});write(d);res.json({ok:true})});
app.post("/api/event",auth,mayor,(req,res)=>{let d=read(),title=(req.body.title||"").trim(),text=(req.body.text||"").trim();if(!title||!text)return res.status(400).json({error:"Preencha os campos."});d.events.unshift({id:Date.now(),title,text,date:new Date().toLocaleDateString("pt-BR")});write(d);res.json({ok:true})});
app.post("/api/tax",auth,mayor,(req,res)=>{let d=read(),tax=Number(req.body.tax);if(!Number.isFinite(tax)||tax<0||tax>30)return res.status(400).json({error:"Use de 0% a 30%."});d.city.tax=tax;d.city.treasury+=Math.round(d.city.population*tax*2);d.city.quality=Math.max(0,Math.min(100,70+Math.round((10-tax)*2)));write(d);res.json({ok:true})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("Sorokiba rodando na porta "+PORT));